/**
 * GENERATED by design/build_tokens.py from design/tokens.json. Do not edit by hand.
 *
 * The web app gets the same tokens as CSS custom properties; React Native has no cascade,
 * so they are plain objects here.
 */

export interface Theme {
  bgPage: string;
  bgCard: string;
  bgEmphasis: string;
  fgPrimary: string;
  fgSecondary: string;
  fgMuted: string;
  border: string;
  accent: string;
  accentText: string;
  highlight: string;
  chartSurface: string;
  gridline: string;
  baseline: string;
  fgOnAccent: string;
}

export const light: Theme = {
  bgPage: '#F6F7FA',
  bgCard: '#FFFFFF',
  bgEmphasis: '#EAF0FB',
  fgPrimary: '#14171F',
  fgSecondary: '#454C5E',
  fgMuted: '#5A6173',
  border: '#D8DDE8',
  accent: '#003399',
  accentText: '#003399',
  highlight: '#FFCC00',
  chartSurface: '#FFFFFF',
  gridline: '#E3E7F0',
  baseline: '#848CA0',
  fgOnAccent: '#FFFFFF',
};

export const dark: Theme = {
  bgPage: '#0A0F1E',
  bgCard: '#111A31',
  bgEmphasis: '#18264A',
  fgPrimary: '#FFFFFF',
  fgSecondary: '#C6CCDB',
  fgMuted: '#9AA3B8',
  border: '#27324F',
  accent: '#FFCC00',
  accentText: '#A9C0FF',
  highlight: '#FFCC00',
  chartSurface: '#111A31',
  gridline: '#27324F',
  baseline: '#6E7A99',
  fgOnAccent: '#0A0F1E',
};

export const Brand = {
  euBlue: '#003399',
  euGold: '#FFCC00',
  euDeep: '#00205B',
} as const;

/** Type scale, matching `--text-axis`, `--text-body` and `--text-stat` on the web. */
export const Text = {
  axis: 11,
  body: 14,
  stat: 30,
  title: 22,
  heading: 17,
} as const;

/**
 * `useColorScheme()` returns 'unspecified' as well as 'light', 'dark' and null, so the parameter
 * is deliberately wider than the two themes: anything that is not dark renders light.
 */
export const themeFor = (scheme: string | null | undefined): Theme =>
  scheme === 'dark' ? dark : light;
