/**
 * The model, loaded once.
 *
 * `assets/data/eu27.json` is a copy of `web/public/data/eu27.json`, the bundle written by
 * `model/export_json.py`. It is ~288 KB and every screen is a pure function of it, so the app
 * ships it and needs no network at all: no API, no Supabase, no first-run fetch, and no
 * difference between what the phone shows offline and what the site shows online.
 *
 * `__tests__/parity.test.ts` fails if this copy and the web one drift, which is the failure
 * mode a copy invites -- a bundle regenerated by `./run.sh data` and committed on the web side
 * only would leave the app quietly reporting last month's figures.
 */
import type { Bundle, Country } from './types';

export const bundle = require('../../assets/data/eu27.json') as Bundle;

/** Every country, in the order the site lists them: alphabetically by name. */
export const countries: Country[] = Object.values(bundle.countries).sort((a, b) =>
  a.name.localeCompare(b.name)
);

export const countryFor = (iso: string | undefined): Country | undefined =>
  iso ? bundle.countries[iso.toUpperCase()] : undefined;

/** Case-insensitive match on name or ISO code, for the list screen's filter. */
export function search(query: string): Country[] {
  const q = query.trim().toLowerCase();
  if (!q) return countries;
  return countries.filter(c => c.name.toLowerCase().includes(q) || c.iso2.toLowerCase().includes(q));
}
