#!/usr/bin/env python3
"""
Generate every output's design tokens from `design/tokens.json` (DECISIONS.md #74, #76).

    python3 design/build_tokens.py           # write the three generated files
    python3 design/build_tokens.py --check   # exit 1 if any generated file is stale

Writes:
    web/src/styles/tokens.css        Tailwind @theme block plus the dark-mode overrides
    book/templates/tokens.typ        colours and type for the typst PDFs
    mobile/src/constants/Colors.ts   the React Native theme objects

Before writing anything it checks WCAG 2.2 contrast for the pairs listed in tokens.json
(4.5:1 for text, 3:1 for UI), in both themes. A palette that fails is not generated: the
old way, a hex edited in one of four places, is how a 3.21:1 muted grey shipped as body text.

Standard library only, like the rest of the model.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "design" / "tokens.json"
CSS = ROOT / "web" / "src" / "styles" / "tokens.css"
TYP = ROOT / "book" / "templates" / "tokens.typ"
MOBILE = ROOT / "mobile" / "src" / "constants" / "Colors.ts"

BANNER = "GENERATED by design/build_tokens.py from design/tokens.json. Do not edit by hand."


def luminance(hex_colour: str) -> float:
    h = hex_colour.lstrip("#")
    channels = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    lin = [c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]


def contrast(a: str, b: str) -> float:
    la, lb = sorted((luminance(a), luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def check_contrast(tokens: dict) -> list[str]:
    failures = []
    for theme, colours in tokens["themes"].items():
        for kind, floor in (("text", 4.5), ("ui", 3.0)):
            for fg, bg in tokens["contrast"][kind]:
                ratio = contrast(colours[fg], colours[bg])
                if ratio < floor:
                    failures.append(f"{theme}: {fg} on {bg} is {ratio:.2f}:1, below {floor}:1 ({kind})")
    return failures


def kebab(name: str) -> str:
    return name.replace("_", "-")


def camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(p.title() for p in rest)


def css(tokens: dict) -> str:
    light, dark = tokens["themes"]["light"], tokens["themes"]["dark"]
    px = tokens["type"]["px"]
    lines = [f"/* {BANNER} */", "", "@theme {"]
    lines += [f"  --color-{kebab(k)}: {v};" for k, v in tokens["brand"].items()]
    lines += [f"  --color-{kebab(k)}: {v};" for k, v in light.items()]
    lines += [f"  --text-{k}: {v}px;" for k, v in px.items() if k in ("axis", "body", "stat")]
    # The print serif, for display type on the web too: the site and the PDFs share one voice.
    serif = ", ".join(f'"{n}"' if " " in n else n for n in tokens["type"]["print_family"]) + ", serif"
    lines += [f"  --font-serif: {serif};"]
    lines += ["}", ""]
    dark_block = [f"    --color-{kebab(k)}: {v};" for k, v in dark.items()]
    lines += ["@layer base {", "  @media (prefers-color-scheme: dark) {",
              "    :root:not([data-theme='light']) {"]
    lines += ["  " + l for l in dark_block]
    lines += ["    }", "  }", "", "  :root[data-theme='dark'] {"]
    lines += dark_block
    lines += ["  }", "}", ""]
    return "\n".join(lines)


def typ(tokens: dict) -> str:
    t = tokens["type"]
    family = lambda names: "(" + ", ".join(f'"{n}"' for n in names) + ")"
    lines = [f"// {BANNER}", ""]
    lines += [f'#let {kebab(k)} = rgb("{v}")' for k, v in tokens["brand"].items()]
    lines += [f'#let {kebab(k)} = rgb("{v}")' for k, v in tokens["print"].items()]
    lines += [f'#let {kebab(k)}-light = rgb("{v}")' for k, v in tokens["themes"]["light"].items()]
    lines += [f"#let print-family = {family(t['print_family'])}",
              f"#let print-mono = {family(t['print_mono'])}"]
    lines += [f"#let size-{kebab(k)} = {v}pt" for k, v in t["pt"].items()]
    return "\n".join(lines) + "\n"


def mobile(tokens: dict) -> str:
    light, dark = tokens["themes"]["light"], tokens["themes"]["dark"]
    keys = list(light)
    obj = lambda theme: "\n".join(f"  {camel(k)}: '{theme[k]}'," for k in keys)
    px = tokens["type"]["px"]
    return "\n".join([
        f"/**\n * {BANNER}\n *\n * The web app gets the same tokens as CSS custom properties; React Native has no cascade,\n"
        " * so they are plain objects here.\n */",
        "",
        "export interface Theme {",
        *[f"  {camel(k)}: string;" for k in keys],
        "}",
        "",
        "export const light: Theme = {",
        obj(light),
        "};",
        "",
        "export const dark: Theme = {",
        obj(dark),
        "};",
        "",
        "export const Brand = {",
        *[f"  {camel(k)}: '{v}'," for k, v in tokens["brand"].items()],
        "} as const;",
        "",
        "/** Type scale, matching `--text-axis`, `--text-body` and `--text-stat` on the web. */",
        "export const Text = {",
        *[f"  {k}: {v}," for k, v in px.items()],
        "} as const;",
        "",
        "/**",
        " * `useColorScheme()` returns 'unspecified' as well as 'light', 'dark' and null, so the parameter",
        " * is deliberately wider than the two themes: anything that is not dark renders light.",
        " */",
        "export const themeFor = (scheme: string | null | undefined): Theme =>",
        "  scheme === 'dark' ? dark : light;",
        "",
    ])


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true", help="fail if a generated file is stale")
    args = p.parse_args(argv)

    tokens = json.loads(SOURCE.read_text(encoding="utf-8"))
    failures = check_contrast(tokens)
    if failures:
        print("contrast check failed:\n  " + "\n  ".join(failures), file=sys.stderr)
        return 1

    outputs = {CSS: css(tokens), TYP: typ(tokens), MOBILE: mobile(tokens)}
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, text in outputs.items()
                 if not path.exists() or path.read_text(encoding="utf-8") != text]
        if stale:
            print("stale, run python3 design/build_tokens.py: " + ", ".join(stale), file=sys.stderr)
            return 1
        return 0
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
